name: Robot Framework Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Robot Tests
    runs-on: ubuntu-latest

    container:
      image: jussaragranja/robotframework-fedora

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          robot -d results test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
